### ISSUE TITLE
Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only LOOP

### ISSUE THREAD

**Issue by wuast94** [HaveAGitGat/Tdarr_Plugins#312] opened 2022-05-22 09:44 UTC
I tried using this Plugin  and stuck in a loop, i updated everthing but no luck. 

```
2022-05-22T11:23:05.555Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:[Step W04] [C3] Preparing command
2022-05-22T11:23:05.556Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Cache file stem: /temp
2022-05-22T11:23:05.557Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Cache file path: /temp/Placeholder Disk-2160p-TdarrCacheFile-D20c3J5ywg.mkv
2022-05-22T11:23:05.558Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Create transcode args
2022-05-22T11:23:05.559Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Args: -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid -i /temp/Placeholder Disk-2160p-TdarrCacheFile-g3J3Sy_loK.mkv -map 0:v -map 0:a -map 0:s? -map -:d? -c copy -c:v:0 hevc_nvenc -preset medium -profile:v main10 -rc-lookahead 32 -spatial_aq:v 1 -aq-strength:v 8 -max_muxing_queue_size 4096 -b:v 3480164 -maxrate 4524213 -minrate 2436115 -bufsize 41208431 -map_metadata:g -1 /temp/Placeholder Disk-2160p-TdarrCacheFile-D20c3J5ywg.mkv
2022-05-22T11:23:05.560Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Getting source file size
2022-05-22T11:23:05.561Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Source file size: 3.9979208260774612
2022-05-22T11:23:05.563Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Performing safety check on worker config to see if old transcode args/container match new ones
2022-05-22T11:23:05.564Z jkbz_geH7xb:Node[P1000]:Worker[sFtxi-srh]:Safety check [-error-]:The new transcode arguments were the exact same as the last ones meaning
2022-05-22T11:23:05.564Z the file/worker would most likely be stuck in an infinite transcode loop if not stopped.
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z Last arguments: -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid ,-map 0:v -map 0:a -map 0:s? -map -:d? -c copy -c:v:0 hevc_nvenc -preset medium -profile:v main10 -rc-lookahead 32 -spatial_aq:v 1 -aq-strength:v 8 -max_muxing_queue_size 4096 -b:v 3480164 -maxrate 4524213 -minrate 2436115 -bufsize 41208431 -map_metadata:g -1 in .mkv
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z New arguments: -vsync 0 -hwaccel cuda -hwaccel_output_format cuda -c:v hevc_cuvid ,-map 0:v -map 0:a -map 0:s? -map -:d? -c copy -c:v:0 hevc_nvenc -preset medium -profile:v main10 -rc-lookahead 32 -spatial_aq:v 1 -aq-strength:v 8 -max_muxing_queue_size 4096 -b:v 3480164 -maxrate 4524213 -minrate 2436115 -bufsize 41208431 -map_metadata:g -1 in .mkv
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z Plugin Community Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z Check your plugin stack or transcode settings to make sure that you have conditions to prevent an infinite transcode loop
2022-05-22T11:23:05.564Z
2022-05-22T11:23:05.564Z
```
![image](https://user-images.githubusercontent.com/16965460/169689394-ff574369-ceff-4dcc-b5ad-c66dcafe53d6.png)

Someone an idea what i missed ?

**Comment by HaveAGitGat** [comment] 2022-05-22 16:59
Please post the full job report as it contains lots of useful info :)

**Comment by wuast94** [comment] 2022-05-22 18:48
[jkbz_geH7xb-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/8750057/jkbz_geH7xb-log.txt)
[bDbqSW2nwnR-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/8750060/bDbqSW2nwnR-log.txt)

Hope this helps :)

**Comment by HaveAGitGat** [comment] 2022-05-23 18:52
Thanks, it's due to this plugin:
`Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only`

Disable it for now and use the Migz one if you can, I'll have a closer look tomorrow.

**Comment by wuast94** [comment] 2022-05-23 18:57
> Thanks, it's due to this plugin: `Tdarr_Plugin_A47j_FFMPEG_NVENC_HEVC_Video_Only`
> 
> Disable it for now and use the Migz one if you can, I'll have a closer look tomorrow.

Yes, the migz one was working fine for other library's, but on this one I want the following: 
1. Convert all to h265 with nvenc 
2. Downscale 4k and higher to 1080p but don't upscale anything

And if I'm right this plugin (should) exactly do what I want 

I stopped any transcode anyway and resume when we got this fixed :) so no stress, Im thankfull for all the work 😊

**Comment by HaveAGitGat** [comment] 2022-05-26 13:26
The issue is to do with MediaInfo not collecting the stream bitrate correctly.

If you check the first file version, the overall bitrate its 46Mb/s and the video stream bitrate is 41Mb/s. The file is transcoded and the new overall bitrate is 8.4Mb/s (correct) and the video stream bitrate is still 41Mb/s (incorrect), so the plugin runs again as the video bitrate is still too high.

This is fixed by running mkvpropedit on the new file, which I've added to the next version (.19).

**Comment by pwoxisolutions** [comment] 2022-05-27 22:53
I am looking for this fix as well. If its a script based fixed can you update the plugin/script JS file. Or do we need to wait for .19 to come in?

I am in process of doing 40tb 1080p to 720p archives. This is the only plugin I was able to find to resize the video resolution (if you know of other to resize all videos to 720p x265 please let me know). 

If its platform .19 change when do we expect Docker build for it?

Thank you for your help.

**Comment by Wolbaz** [comment] 2022-06-18 16:34
Any chance we can get the updated version on github? I'd like to fix this on my setup if possible.

**Comment by Wolbaz** [comment] 2022-06-18 19:01
Has any progress been made on this?

**Comment by mikiline-ONE** [comment] 2022-09-05 09:36
> This is fixed by running mkvpropedit on the new file, which I've added to the next version (.19).

are there some updates ?
community still have version 1.1

thx, regards

**Comment by Jessomadic** [comment] 2022-09-27 02:04
@HaveAGitGat any chance that could be uploaded?

**Comment by Kooramah** [comment] 2022-10-27 02:32
Would love to get an update on this as well. This plugin works really well, just need to fix the loop

**Comment by Kooramah** [comment] 2022-10-28 02:32
@HaveAGitGat is there a way to tell us what the fix is? If so, please share. If its just a change on the plugin, let us know what needs to be modified

**Comment by ArchemedIan** [comment] 2022-10-28 10:49
@Kooramah 
> This is fixed by running mkvpropedit on the new file, which I've added to the next version (.19).

**Comment by Kooramah** [comment] 2022-10-28 12:26
> @Kooramah they did
> 
> > This is fixed by running mkvpropedit on the new file, which I've added to the next version (.19).

Yep, this was mentioned on the 26th of May but since this was announced 5 months ago. The community version hasn’t been touched in 8 months. 

Current docker version is .18

**Comment by ArchemedIan** [comment] 2022-10-31 21:08
>Yep, this was mentioned on the 26th of May but since this was announced 5 months ago. The community version hasn’t been touched in 8 months.

Yep, and then, on the 27th of october, you asked
 >  is there a way to tell us what the fix is? If so, please share.
 > If its just a change on the plugin, let us know what needs to be modified
 
They did share what the fix was, on the 26th of May, as you said..... 

you can keep waiting months or longer, if ever... 
or spend 20 mins copying the plugin to local and figuring out how to write a line in the plugin to rum mkvpropedit.

**Comment by totalisator** [comment] 2022-12-17 18:25
> They did share what the fix was, on the 26th of May, as you said.....
> 
> you can keep waiting months or longer, if ever... or spend 20 mins copying the plugin to local and figuring out how to write a line in the plugin to rum mkvpropedit.

Can someone explain how to do this?
I'm not into rewriting code so this proves to be really difficult for me so pleaso someone explain how to do this.

Even better would be if the fixed version .19 could be put online.

**Comment by daveb92** [comment] 2022-12-26 16:04
I am also seeing this issue but not sure how to add the extra check to the plug-in. Any help appreciated.

**Comment by HaveAGitGat** [comment] 2023-02-16 05:53
Apologies, 2.00.19 was released on Sunday and runs mkvpropedit on the new file so should be fixed now.

**Closed by HaveAGitGat** 2023-02-16 05:53 UTC

**Comment by wuast94** [comment] 2023-02-19 00:04
I´m on 2.00.19 now but cant see any difference. Still stuck in loop´s. 
I tried to check this and the plugins repo but booth don't changed anything, the plugin itself shows last update last year and the main repo was 2 weeks ago.

just to be safe I removed the plugin from stack, deleted local copy, updated community plugins and made then a copy from the plugin, added it to the stack  and enabled the library again.

searched for mkvpropedit in booth repos and had only 2 hits on different plugins.

[kGva-AeRp-log.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/10775411/kGva-AeRp-log.txt)

**Comment by stojg** [comment] 2023-02-21 04:32
FYI, I've added this to my local version and it ... seem to be working

```
if (file.container === "mkv") {
    try {
      const proc = require("child_process");
      proc.execSync(
        `${otherArguments.mkvpropeditPath} --add-track-statistics-tags "${file._id}"`
      );
    } catch (err) {
      response.infoLog += `Error running mkvpropedit: ${err}\n`;
    }
  }
```

**Comment by mikiline-ONE** [comment] 2023-02-21 10:37
@stojg and where did you edit it ? inside a function or at the end of the code?

**Comment by HaveAGitGat** [comment] 2023-02-21 18:11
Thanks @wuast94. In the log you can see

```
2023-02-19T00:55:56.131Z kGva-AeRp:Node[P1000]:Worker[WeQ_hM3_3]:Updating file properties using mkvpropedit
2023-02-19T00:55:56.132Z kGva-AeRp:Node[P1000]:Worker[WeQ_hM3_3]:Updated file properties using mkvpropedit
```

so it definitely seems to be running. I used the same command as @stojg so seems odd that the results seem different

**Comment by wuast94** [comment] 2023-02-21 18:14
Is there any information I can provide to help on this ? Something must be odd, but what ? @HaveAGitGat

**Comment by CrypticMetaphor** [comment] 2023-04-20 12:59
This item is marked as closed, but it is an issue that still persists.

After trying to get support from the discord, it is agreed that "mkvpropedit" doesn't appear to be working correctly.

**Comment by Kooramah** [comment] 2023-04-22 20:16
I gave up on this plugin, last time I used it was probably a few weeks ago where it was throwing errors. The logs show that it didn't like a specific line on the code. I don't have the log in hand, I just gave up on it and moved on using Drakes method and expanded using it

**Comment by CrypticMetaphor** [comment] 2023-04-23 11:16
> I gave up on this plugin, last time I used it was probably a few weeks ago where it was throwing errors. The logs show that it didn't like a specific line on the code. I don't have the log in hand, I just gave up on it and moved on using Drakes method and expanded using it

@Kooramah Could you elaborate Drake's method?
