### ISSUE TITLE
Queue not progressing when using Tdarr_Plugin_c0r1_SetDefaultAudioStream

### ISSUE THREAD

**Issue by Centurix** [HaveAGitGat/Tdarr_Plugins#72] opened 2020-05-14 15:12 UTC
I setup the library with the Tdarr_Plugin_c0r1_SetDefaultAudioStream plugin to select the stereo track in each file. It starts processing and then after 10 or so files the queue count jumps back up to where it started and re-queues the same files over and over again. Like if I have a queue of 1000 items to process, it'll only work on the first 10 files over and over again. It only happens with this plugin. 

I turned on verbose logging and captured a section, all files in the log are re-queued after processing. The only plugin selected for the library is the Tdarr_Plugin_c0r1_SetDefaultAudioStream with a value of 2:

[log_snippet.txt](https://github.com/HaveAGitGat/Tdarr_Plugins/files/4629264/log_snippet.txt)

Each file contains a stereo track to select as default.

**Comment by SpencerReiter** [comment] 2020-06-06 00:21
Are you still having this problem? I am unable to reproduce this issue.

I never tested this plugin with AVI files, it is possible that the "disposition" metadata is not actually available in the ffProbe data returned to the plugin, if this is the case then this situation may be possible.

It is confusing because Tdar sends your video file back through the plugin chain until it passes all of the checks, with you queue of 1000, do you have 10 workers running? Are the files being marked as successful and then later being reprocessed?

**Comment by HaveAGitGat** [comment] 2021-12-15 05:12
Reopen if needed.

**Closed by HaveAGitGat** 2021-12-15 05:12 UTC
